version: '3'
services:
    mathenger-ui:
        build:
            context: mathenger-ui
            dockerfile: Dockerfile
            args:
                REACT_APP_API_BASE_URL: http://127.0.0.1:8081
                REACT_APP_WEB_SOCKET_CONNECTION_URL: ws://127.0.0.1:8081/socket
        ports:
        - "80:80"
        restart: always
        depends_on:
          - mathenger-api
        networks:
            - frontend
    mathenger-api:
        build: 
            context: mathenger-api
            dockerfile: Dockerfile
        ports: 
            - "8081:8081"
        restart: always
        depends_on: 
            - db
        environment: 
            SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mathenger
            SPRING_DATASOURCE_USERNAME: admin
            SPRING_DATASOURCE_PASSWORD: password
            MATHENGER_BASE_URL: http://localhost:8081/
        networks: 
            - backend
            - frontend
    db:
        image: mysql:8.0.19
        ports: 
            - "3306:3306"
        restart: always
        environment: 
            MYSQL_DATABASE: mathenger
            MYSQL_USER: admin
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        volumes: 
            - db-data:/var/lib/mysql
        networks: 
            - backend
volumes: 
    db-data:
networks: 
    backend:
    frontend:
